"""Email processing and categorization using Claude"""
from anthropic import Anthropic
import config
from datetime import datetime


class EmailProcessor:
    def __init__(self):
        self.client = Anthropic(api_key=config.ANTHROPIC_API_KEY)

    def categorize_and_summarize(self, emails):
        """
        Categorize and summarize emails using Claude

        Args:
            emails: List of email dictionaries

        Returns:
            Dictionary with categorized summaries
        """
        if not emails:
            return None

        # Prepare email content for Claude
        email_text = self._format_emails_for_analysis(emails)

        # Create the prompt
        prompt = f"""You are an email categorization and summarization assistant.

I need you to:
1. Categorize each email into one of these categories:
   - Amazon Advertising
   - Listing Optimization
   - Recent Trends in Amazon
   - AI Trends connected to Amazon
   - Other AI Trends
   - Uncategorized

2. Provide a concise summary of each email (2-3 sentences max)

3. Group the summaries by category

Here are the emails to process:

{email_text}

Please provide the output in the following format:

## Category Name

### Email Subject
**From:** Sender
**Summary:** Brief summary here

(Repeat for each category that has emails)

At the end, provide a brief executive summary of the most important items across all categories."""

        # Call Claude API
        message = self.client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=4000,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        return message.content[0].text

    def _format_emails_for_analysis(self, emails):
        """Format emails into a readable text block for Claude"""
        formatted = []

        for i, email in enumerate(emails, 1):
            # Truncate body if too long (keep first 1000 chars)
            body = email['body'][:1000] + "..." if len(email['body']) > 1000 else email['body']

            formatted.append(f"""
--- Email {i} ---
Subject: {email['subject']}
From: {email['sender']}
Date: {email['date']}
Body:
{body}
""")

        return "\n".join(formatted)

    def create_html_summary(self, categorized_summary, email_count):
        """Create an HTML formatted email summary"""
        current_date = datetime.now().strftime("%B %d, %Y")

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #3498db;
            margin-top: 30px;
        }}
        h3 {{
            color: #34495e;
            margin-top: 20px;
        }}
        .meta {{
            color: #7f8c8d;
            font-size: 14px;
        }}
        .summary {{
            background-color: #ecf0f1;
            padding: 15px;
            border-left: 4px solid #3498db;
            margin: 10px 0;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            color: #7f8c8d;
            font-size: 12px;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📧 CESPOO Daily Email Summary</h1>
        <p class="meta"><strong>Date:</strong> {current_date}</p>
        <p class="meta"><strong>Emails Processed:</strong> {email_count}</p>

        <div class="summary">
            {categorized_summary.replace('##', '<h2>').replace('###', '<h3>').replace('**', '<strong>').replace('**', '</strong>')}
        </div>

        <div class="footer">
            <p>Generated by CESPOO - Claude Email Summarization and Priority On-demand Offloading</p>
            <p>This summary was processed from {config.SOURCE_EMAIL}</p>
        </div>
    </div>
</body>
</html>
"""
        return html
